version: '3.5'
services:

  example-provider:
    build: .
    environment:
      - PAPIEA_ADMIN_S2S_KEY=foshoh2A
      - PAPIEA_URL=http://papiea:3000
    depends_on: 
      - papiea

  papiea:
    image: nutanix-docker.jfrog.io/papiea:941
    depends_on:
      - mongo
    environment:
      - PAPIEA_ADMIN_S2S_KEY=foshoh2A
      - PAPIEA_PUBLIC_URL=http://127.0.0.1:3333
    ports:
      - "3333:3000"

  mongo:
    image: mongo:4.1
